---
- name: Reload and restart lidi-receive
  ansible.builtin.systemd:
    name: lidi-receive.service
    state: restarted
    daemon_reload: true

- name: Reload sysctl
  ansible.builtin.command:
    cmd: sysctl --system
  changed_when: true
